#!/usr/bin/env python3
"""The house rule, checked in CI: every printed block in a chapter's lab section is verbatim
output of the lab that produced it. Generated by the book's publishing tool; do not edit."""
import re
import subprocess
import sys

CHAPTERS = {'01-one-small-step.md': 'labs/ch01_one_small_step_lab.py', '02-the-ghost-in-the-loop.md': 'labs/ch02_the_ghost_in_the_loop_lab.py'}
HEADING = '^## (\\d+)\\.\\d+ Lab: (.+)$'
FENCE = 'text'


def contiguous(block, real):
    b = [l.rstrip() for l in block]
    r = [l.rstrip() for l in real]
    segs, cur = [], []
    for l in b:
        if l.strip() == "...":
            segs.append(cur)
            cur = []
        else:
            cur.append(l)
    segs.append(cur)
    pos = 0
    for seg in segs:
        if not seg:
            continue
        found = next((i for i in range(pos, len(r) - len(seg) + 1) if r[i:i + len(seg)] == seg), None)
        if found is None:
            return False
        pos = found + len(seg)
    return True


def main():
    bad = total = 0
    for md, lab in CHAPTERS.items():
        text = open("chapters/" + md).read()
        real = subprocess.run([sys.executable, lab], capture_output=True, text=True, check=True).stdout.rstrip("\n").split("\n")
        m = re.search(HEADING, text, re.M)
        sec = text[m.start():]
        nxt = re.search(r"^## ", sec[1:], re.M)
        sec = sec[:nxt.start() + 1] if nxt else sec
        for fm in re.finditer(r"^```([^\n]*)\n(.*?)^```[ \t]*$", sec, re.S | re.M):
            if fm.group(1).strip() != FENCE:
                continue
            total += 1
            lines = fm.group(2).rstrip("\n").split("\n")
            if not contiguous(lines, real):
                bad += 1
                print(f"NOT VERBATIM in {md}: block starting {lines[0][:60]!r}")
    print(f"{total} printed blocks checked, {bad} not verbatim")
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
